#define MAXICON				500

#define IDM_CONFIGURE		1001
#define IDM_HELP			1002
#define IDM_HELPSEARCH		1003
#define IDM_HELPTS			1004
#define IDM_ABOUT			1005
#define IDM_FONT			1006

#define CONFIGDLGBOX		101
#define ABOUTDLGBOX         102
#define FONTDLGBOX          103

#define IDC_DATE            2000
#define IDC_TIME            2001
#define IDC_MEMORY          2002
#define IDC_GDI             2003
#define IDC_USER            2004
#define IDC_DOSMEM          2005
#define IDC_TOPMOST         2006
#define IDC_STATIC            -1

#define IDC_AMPM			2010
#define IDC_UT				2011

