// $Header:   P:/PVCS/MAX/MAXEDIT/CVERSION.H_V   1.9   10 Jul 1996 10:59:16   BOB  $
//
// CVERSION.H - component version info file for MaxEdit
//
// ---------------------------------------------------------
// Copyright (C) 1995 Qualitas, Inc.  GNU General Public License version 3
// ---------------------------------------------------------

#include <ver.h>					// Version resource definitions from DDK
#include <maxnames.h>

#define VER_MODULE					11
#define VER_MODULE_STR				"011"

#define VER_FILETYPE				VFT_APP
#define VER_FILESUBTYPE 			VFT2_UNKNOWN
#define VER_FILEDESCRIPTION_STR 	"Qualitas MaxEdit"
#define VER_INTERNALNAME_STR		"MAXEDIT"
#define VER_ORIGINALFILENAME_STR	"MAXEDIT.EXE"
