//' $Header:   P:/PVCS/MAX/DOSMAX32/RESOURCE.H_V   1.3   26 Feb 1996 12:50:18   BOB  $
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DOSMAX32.RC
//
#define IDS_HELPTEXT1                   1
#define IDS_HELPTEXT2                   2
#define IDS_HELPTEXT3                   3
#define IDS_HELPTEXT4                   4
#define IDS_HELPTEXT5                   5
#define IDS_HELPTEXT6                   6
#define IDS_HELPTEXT7                   7
#define IDS_HELPTEXT8                   8
#define IDS_HELPTEXT9                   9
#define IDS_HELPTEXT10                  10
#define IDS_HELPTEXT11                  11
#define IDS_HELPTEXT12                  12
#define IDS_HELPTEXT13                  13
#define IDS_HELPTEXT14                  14
#define IDS_INIFILENAME                 15
#define IDS_INISECTNAME                 16
#define IDS_MENUSHORTCUT                17
#define IDS_PSPTITLE                    18
#define IDS_SHORTCUTTO                  19
#define IDS_INICFGSECT                  20
#define IDS_INIMAXPATH                  21
#define IDS_SETEWVNAME                  22
#define IDS_UNABLEFF                    23
#define IDS_UNABLEREG                   24
#define IDD_PIFPAGE                     132
#define IDC_DEFAULT                     1000
#define IDC_ON                          1001
#define IDC_OFF                         1002
#define IDC_HELPTEXT                    1003
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
