#' $Header:   P:/PVCS/MAX/RAMBASIC/MAKEFILE.__V   1.3   30 May 1997 12:13:38   BOB  $
#
# Makefile for RAMBASIC
#

!include $(MAXROOT)include\maxnames.mak

OEM=ret 			# Default 3-letter OEM name
PRODNAME=rambasic	# Product file basename

O=$(OEM)\			# OEM-specific files
R=				# Source directory

OLDINC=$(INCLUDE)		# Previous INCLUDE value
ALLINC=$(O);$(I);$(Q);$(INCLUDE) # INCLUDE search path

# if LST is defined in the environment or on the command line,
# define a macro we can tack onto the end of each MASM line
!IFDEF LST
LSTMAC=,$(LST)\$(@B)
!ELSE
LSTMAC=
!ENDIF

AFLAGS=/mu /p /r /t /w1 /DLANG_$(LANG) # MASM options
LFLAGS=/map /line /nod		# Linker options

{$(R)}.asm{$(O)}.obj:
	 set INCLUDE=$(ALLINC)
	 masm $(R)$(@B) $(AFLAGS), $(O) $(LSTMAC);
	 set INCLUDE=$(OLDINC)

OBJS=	 $(O)RAMBASIC.OBJ

ALL:	 DIR	$(O)$(PRODNAME).COM	$(BD)$(PRODNAME).COM

DEL:
	-rm $(O)*.*

DIR:
	vdir -c $(O)

pvcs.cfg:
	@echo <<pvcs.cfg
REFERENCEDIR=WRITEPROTECT P:\MAX\rambasic\*
VCSDIR = P:\PVCS\MAX\rambasic\*
ALIAS ALL P:\PVCS\MAX\rambasic\*.*,p:\pvcs\max\rambasic\udlocal2.bav
<<KEEP

GET: pvcs.cfg
	$(GETCMD) $(MAKEDIR)

DEPSCAN: makefile
	depscan *.asm >rambdep.inc

makefile: rambdep.inc

!include rambdep.inc

$(O)$(PRODNAME).COM:	 $(OBJS)	makefile
	 $(LD) @<<$(O)$(PRODNAME).arf
		$(OBJS: =+^
)
		$*.exe
		$*.map
		$(LFLAGS)
		NUL.def
<<KEEP
	 mapssf -t$*.ssf $*.map
	 exe2bin $* $*.com
	 del $*.exe

$(BD)$(PRODNAME).COM: $(O)$(PRODNAME).COM
	 xc /r	 $(**R).COM	$*.*
	 xc /r	 $(**R).SSF	$*.*
	 xc /r	 $(**R).MAP	$*.*

$(O)RAMBASIC.OBJ: RAMBASIC.ASM $(RAMBASIC_ADEP)

