// $Header:   P:/PVCS/MAX/MAXSETUP/CVERSION.H_V   1.30   26 Mar 1996 08:50:32   PETERJ  $
//
// CVERSION.H - component version info file for MaxSetup
//
// ---------------------------------------------------------
// Copyright (C) 1995 Qualitas, Inc.  All rights reserved
// ---------------------------------------------------------

#include <ver.h>					// Version resource definitions from DDK
#include <maxnames.h>

#define VER_MODULE					32
#define VER_MODULE_STR				"032"

#define VER_FILETYPE				VFT_APP
#define VER_FILESUBTYPE 			VFT2_UNKNOWN
#define VER_FILEDESCRIPTION_STR 	"Qualitas Max Setup"
#define VER_INTERNALNAME_STR		"Setup"
#define VER_ORIGINALFILENAME_STR	"SETUP.EXE"
