
#define IDD_BOOTUP              100
#define IDD_VIDEO               200
#define IDD_DPMI                300
#define IDD_UNINSTALL           400
#define IDD_BASEDIALOG          600
#define IDHELP                  603

#define EXITDLGBOX		700

#define IDC_QMT			101
#define IDC_EXTRADOS		102
#define IDC_COMPRESS		103
#define IDC_DOSMAX		104
#define IDC_MAXMETER		105
#define IDC_IMULTISECTION	106
#define IDC_RMULTISECTION	107

#define IDC_MONOCHROME		201
#define IDC_VGASWAP		202

#define IDC_DPMI		301
#define IDC_DPMISWAP		302
#define IDC_SWAPFILE		303
#define IDC_SWAPSIZE		304
#define IDC_EMS			305
#define IDC_PAGEFRAME		306

#define IDC_UNINSTALLMAX        601
#define IDC_STRIPLOAD           602
#define IDC_STRIPQMT            602

