
;***************************************************************************

;-------------- Command flags ---------------------

@CMD_GSIZE	equ 8000h	; Getsize has been requested (?)
@CMD_DEAD_DEV	equ 4000h	; DEVICE=  deadman switch
@CMD_DEAD_INS	equ 2000h	; INSTALL= deadman switch
@CMD_VERBOSE	equ 1000h	; VERBOSE option (display copyright)

COMMENT |

Flag descriptions:


|


