PATH C:\DOS;c:\ftp30;C:\BIN
PROMPT $P$G
set PCTCP=c:\ftp31\pctcp.ini
C:\386MAX\386load size=18848 flexframe prog=c:\ftp31\lsl
C:\386MAX\386load size=39456 prgreg=2 flexframe prog=c:\ftp31\smc8000
C:\386MAX\386load size=40384 prgreg=2 flexframe prog=c:\ftp31\ipxodi
rem c:\ftp31\netx
C:\386MAX\386load size=7536 flexframe prog=c:\ftp31\odipkt
c:\ftp31\ethdrv -p 12
rem i9
rem c:alarm -m 6 -r
