//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by DRVELSE.RC
//
#define IDS_STARTUPGRP                  1
#define IDS_US_STARTUPGRP               1
#define IDS_DE_STARTUPGRP               2
#define IDD_LOADCLEAR                   101
#define IDI_ICONSTOP                    101
#define IDC_DRVNAME                     1000
#define IDC_NOLOAD                      1001
#define IDC_LOADONCE                    1002
#define IDC_REMOVE                      1003
#define IDC_NOWARN                      1004
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
