# $Header:   P:/PVCS/MAX/INCLUDE/QUALITAS.MAV   1.1   18 Apr 1996 08:05:34   HENRY  $
#
# QUALITAS.MAK - Product names for Qualitas, Inc.
#
# Copyright (C) 1996 Qualitas, Inc.  GNU General Public License version 3
#
# While we don't change the names of product directories, product
# executable names can and often do change - sometimes several times
# in the course of development.
#
# Here's a single place where .EXE and .DLL basenames are defined.
#

DSMGR=dsmgr
FF=ff
WFF=ffw

