//' $Header:   P:/PVCS/MAX/INCLUDE/TRAYNOTE.H_V   1.0   25 Sep 1996 11:14:28   BOB  $

//*******************************************************
//	Tray Notification Application Header
//*******************************************************

// Define user-specific message numbers used in TrayWndProc
#define MYWM_NEWSECTION 		(WM_APP+  0)
#define MYWM_MODSECTION 		(WM_APP+  1)
#define MYWM_ENDSECTION 		(WM_APP+  2)

// Define user-specific message numbers used in DlgProc
#define MYWM_BROWSE 			(WM_APP+100)

//***************************************************************************
//	End of File: TRAYNOTE.H
//***************************************************************************
